meta_product_name: "InstantDoc"
meta_title: "InstantDoc - Secure doctor appointments today"
meta_description: "Simply book your appointment on short notice and skip the wait - you're just a few clicks away."
meta_image: "cover.png" # exists in `app/assets/images/`
