meta_product_name: "InstantDoc"
meta_title: "InstantDoc - Get your doctor's appointment today"
meta_description: "Skip the wait and instantly see a doctor - you're just a few clicks away from your last-minute appointment."
meta_image: "cover.png" # exists in `app/assets/images/`
